### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by xaur** [heyvj/decred-events#1]
Hey here are some quick ideas I had:

* Use lowercase for repository name
* I agree collecting upcoming and past events in one place is good idea. As of best practices, jy-p suggested to place guidelines for events to dcrdocs. I don't know what is best, just FYI.
* "in the next 12 months" -- not so easy, events are usually known only 1 month in advance.
* Report filename: 20180418-Blockchain-Expo-London.md
* Good to see penguins attending.
* I had an idea how to organize future and past event lists to minimize movement from future to past lists. Create a yearly or monthly table and enter events in rows. Each row has (date, city, country, even title, speech title, attending people). When reader is looking at this table he is able to see himself past events by looking at past dates. So when I'll look at list of events for May it will be my job to check calendar and see which are upcoming. A bit inconvenient for the reader but less maintenance for us.
* In event report file, link to all known photos and videos captured on that event

I may post more if time allows.

**Comment by xaur** [comment]
* if to commit images, use small to medium sized to avoid rapid repo size growth. Ideally we'd have our own IPFS node to host full res photos and videos from events
* repo/"Event-Logs" -> "reports"
* wiki/"Events Overview" -> "Upcoming Events"
* wiki/"Best Practices Overview" -> "Best Practices"
* Do not use US-specific AM/PM for time

**Comment by heyvj** [comment]
Thanks for the feedback xaur. I have made many of the changes you suggested and will now close this issue. If you would like to discuss anything furhter please open up a new issue.
