### ISSUE TITLE
The North American Bitcoin Conference in Miami, USA

### ISSUE THREAD

**Issue by Dustorf** [heyvj/decred-events#10]
https://btcmiami.com/

Decred Presence: Jake had a 15 minute speaking slot, title: Applications in Blockchain File-Stamping, full booth sponsorship. https://btcmiami.com/session/applications-of-blockchain-time-stamping/

Team Members Present: jy-p, JZ, DZ, Isaac, Big Red, Zubair, Josh, Anshawblack (local)

Attendance: Estimated by Decred team to be 1,000. Last year was 8,000, promoters set expectations at 6,000, claimed 1,800 after the event

Goals: 
1. Promote Decred to the attendees, Politeia's applications 
2. Gauge conference and event enthusiasm for 2019 - use conclusions to plan events for the remainder of the year
3. Coordinate interviews across media outlets in attendance to promote Decred
4. Meet with others in attendance (institutional investors, other projects, media, etc.)
5. Test new messaging: SoV, Various tag lines, etc.
6. Review old swag & determine what needs updating/what can be disposed of
7. jy-p, JZ, Josh media training with Ditto
8. Evaluate Decred team members for future roles and involvement 

Evaluation of Goals
1. The direct goal of promoting Decred to the conference was a major letdown based upon the number of attendees and the dearth of other high quality projects in attendance. This was a surprise, as the event last year was a major success. A good number of project contributors met Decred last year, including the community organizers just now starting in San Francisco. Jake's presentation was well done and well attended given the conference attendance numbers. Decred did have lots of quality meetings, including dinner with Chris DeRose, who has been very complimentary of Decred lately.
Matt D
Hello Decred Community,

I want to thank Angelo, Jonathan, and the rest of the Decred members that were at The North American Bitcoin Conference for their hospitality.

As a digital marketer in the cryptocurrency space, I’ve had my fair share of project introductions at conferences.

_My experience with Decred at BTC Miami was by far the best._

All the Decred members at the booth were professional, informative, and friendly. I had multiple hour long conversations at the booth where I had the opportunity to ask questions and learn about Decred. Following the insightful conversations, I was sent links to continue my research and received free merchandise as well.

_Jake also had a killer keynote on the main stage_

I'm happy to say I’ve secured my first bag of DCR and I’m currently downloading Decrediton so I can start staking.

I'm very excited to join this community and I’m looking forward to a bright future.

## Photos

https://twitter.com/jz_bz/status/1085906384409878531
https://twitter.com/jz_bz/status/1085944814732861446
https://twitter.com/generalsaccount/status/1085982547539054594
https://matrix.to/#/!aNPTuiryMFmdMQWUzb:decred.org/$15477438448370TAtLj:decred.org
dinner https://twitter.com/treyditto/status/1086269222072725504
https://twitter.com/CryptoCanucks/status/1086386356396441600
https://twitter.com/jz_bz/status/1086460490807570433
https://twitter.com/Decred_ITA/status/1085946325475254273

2. We expected low turnout compared to last year, but this was a dropoff more than we expected. While this may seem a failure, it's a success of the test. We did not make any other commitments to conferences for the remainder of 2019, and we're using this data to adjust our plan. Previously, we had one major event planned per month with the hope of sending a Decred speaker to a second event. We're adjusting our plans to simply one event of this nature per quarter spread across Asia, Europe and the Americas. Dustorf will have more details on this soon in a Politeai proposal and in other channels before that.
3. Interviews were held with Bitsonline, Cheddar, Altcoin Buzz, and CNBC Trader. We met with another media outlet and agreed to work on an exclusive after the event.

## Video

* Interview with @joshuam "Why 2019 will be the biggest year for Decred" https://www.youtube.com/watch?v=Kyihc6Uh4XA
* Interview with jz by CNBC https://www.youtube.com/watch?v=4oKRVXGN6Fs
* Interview with joshuam "Decred Realized Disputes in Blockchain Projects Were Inevitable: Joshua Buirski" https://www.youtube.com/watch?v=CUxDxJ4YAUA
4. 
5. SoV, Secure. Adaptable. Self-Funding, and the accompanying messaging was found to be a very effective way of talking about Decred. It was found to be most clear and impactful.
6. From inventory, we brought keychains, license plate holders, stickers, postcards, handouts, overview booklets, t-shirts, and tote bags. Going forward, we plan to only bring updated booklets, t-shirts and tote bags. This reduction of swag items should make things easier to manage in the future.
7. The team went through media training and found it very useful. So much so, that we have training scheduled for seven further Decred contributors the first week of February.
8. Big Red was determined to not be an Ethereum plant. He was a great part of the team and contributed in a positive way. It was also great to see Zubair at an event, knowing that he's organizing the community with Michael in Toronto. Anshawblack was incredibly valuable because of his Spanish language skills. He also was inspired to begin a Decred podcast with the working title "Decred in Depth", which is a great outcome from getting the team together.

**Comment by heyvj** [comment]
Thanks for this @Dustorf. I've used most of it to create a cleaner write up here (https://github.com/heyvj/decred-events/blob/master/reports/20190116-tnabc-miami.md).

The copied/pasted IMs were too heavy for this format so I have removed them. 

Any feedback on swag (what you took and what was left over) would be useful at this early stage so that we can get more efficient on this front for future events. 

The only other thing that is in the event report template that's missing here is your answer to the question "Would you recommend participating in this event in the future?"

**Comment by xaur** [comment]
Part of the report was a paste from markdown file that broke when pasted as github comment. Some breakage was carried into the file in master, i.e. missing line breaks.
