### ISSUE TITLE
Include events like Token Summit?

### ISSUE THREAD

**Issue by xaur** [heyvj/decred-events#7]
Token Summit is an interesting case. As far as I know nobody attended it from the group of people I refer to as "Decred community". The problem is that I cannot exactly define this group, I only vaguely refer to people who usually actively attend events and participate on Slack #event_planning.

In case of Token Summit, Chris Burniske and Joel Monegro from Placeholder were speaking about governance and Decred. They are not chatting on Slack but I assume they are stakeholders, and I see this as a positive presence of Decred on the event.

**Comment by heyvj** [comment]
Hey xaur,

I understand your question about defining the "Decred community". As far the as the events repo is concerned, if anyone who attends an event and is willing to have an event report written up with a focus on Decred (and ideally following our format), then we should include the report.

For events with no report written up, it's a moot point whether people in attendance were part of the Decred Community.

**Comment by xaur** [comment]
The problem can be reformulated to "What is the criteria to include reports in decred-events?" and then let's try the answer

> if anyone who attends an event and is willing to have an event report written up with a focus on Decred (and ideally following our format), then we should include the report.

Is attendance required?

I think we're looking for a criteria that makes the repo useful. How about:

> This repository accepts reports of all events in _physical space_ where Decred was presented in a significant way.
